### ISSUE TITLE
0.4.0 release todo

### ISSUE THREAD

**Issue by TomasTomecek** [TomasTomecek/sen#92]
* [ ] test sen extensively
 * [ ] write more tests
 * [x] tests
 * [ ] introduce as few changes in behavior as possible with comparison to 0.3.0
 * [ ] document every behavior change
 * [x] autogenerate help for buffers
 * [x] provide help for commands https://github.com/TomasTomecek/sen/commit/77e9977ba0a0d8c5d65db844c47f6ba6fd478829
 * [x] test and polish new features (sort, browser open)
